version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Developer"
      MSSQL_TCP_PORT: "1433"
    ports:
      - "1433:1433"
    volumes:
     - sqlserverdata:/var/opt/mssql
    networks:
      - hlavoj-net


volumes:
  sqlserverdata:

networks:
  hlavoj-net:
    external: true